[phases.setup]
nixPkgs = ["python313", "default-libmysqlclient-dev"]

[phases.install]
cmds = ["python -m venv /app/.venv", "pip install -r requirements.txt"]

[phases.build]
cmds = ["./build.sh"]

[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-8000} RuDjangoProject.wsgi:application"
